### ISSUE TITLE
`check_string': Public key was 32 bytes (Expected 13809239872994541600) (RbNaCl::LengthError)

### ISSUE THREAD

**Issue by thilakg** [GemHQ/round-rb#26]
Ruby version : 2.2.0
Rails version : 4.2.4
Gemfile i added : gem 'round'
then i did bundle install
up to now everything working fine. when i start rails server (bundle exec rails s) i am getting error like this

` ` ` /home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:77: warning: already initialized constant RbNaCl::Box
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:77: warning: previous definition of Box was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:78: warning: already initialized constant RbNaCl::PrivateKey
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:78: warning: previous definition of PrivateKey was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:79: warning: already initialized constant RbNaCl::PublicKey
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:79: warning: previous definition of PublicKey was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:80: warning: already initialized constant RbNaCl::SecretBox
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:80: warning: previous definition of SecretBox was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:81: warning: already initialized constant RbNaCl::SigningKey
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:81: warning: previous definition of SigningKey was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:82: warning: already initialized constant RbNaCl::VerifyKey
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:82: warning: previous definition of VerifyKey was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:83: warning: already initialized constant RbNaCl::GroupElement
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:83: warning: previous definition of GroupElement was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:84: warning: already initialized constant RbNaCl::OneTimeAuth
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:84: warning: previous definition of OneTimeAuth was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-libsodium-1.0.3/lib/rbnacl/libsodium.rb:7: warning: already initialized constant RBNACL_LIBSODIUM_GEM_LIB_PATH
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-libsodium-1.0.3/lib/rbnacl/libsodium.rb:7: warning: previous definition of RBNACL_LIBSODIUM_GEM_LIB_PATH was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:77: warning: already initialized constant RbNaCl::Box
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:77: warning: previous definition of Box was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:78: warning: already initialized constant RbNaCl::PrivateKey
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:78: warning: previous definition of PrivateKey was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:79: warning: already initialized constant RbNaCl::PublicKey
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:79: warning: previous definition of PublicKey was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:80: warning: already initialized constant RbNaCl::SecretBox
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:80: warning: previous definition of SecretBox was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:81: warning: already initialized constant RbNaCl::SigningKey
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:81: warning: previous definition of SigningKey was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:82: warning: already initialized constant RbNaCl::VerifyKey
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:82: warning: previous definition of VerifyKey was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:83: warning: already initialized constant RbNaCl::GroupElement
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:83: warning: previous definition of GroupElement was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:84: warning: already initialized constant RbNaCl::OneTimeAuth
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:84: warning: previous definition of OneTimeAuth was here
/home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl/util.rb:93:in `check_string': Public key was 32 bytes (Expected 13809239872994541600) (RbNaCl::LengthError)
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl/boxes/curve25519xsalsa20poly1305/public_key.rb:28:in `initialize'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl/self_test.rb:16:in `new'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl/self_test.rb:16:in `box_test'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl/self_test.rb:133:in `<top (required)>'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-3.1.2/lib/rbnacl.rb:91:in `<top (required)>'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/rbnacl-libsodium-1.0.3/lib/rbnacl/libsodium.rb:11:in `<top (required)>'
	from /home/moorem/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/runtime.rb:85:in `require'
	from /home/moorem/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/runtime.rb:85:in `rescue in block in require'
	from /home/moorem/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/runtime.rb:68:in `block in require'
	from /home/moorem/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/runtime.rb:61:in `each'
	from /home/moorem/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler/runtime.rb:61:in `require'
	from /home/moorem/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.8.3/lib/bundler.rb:134:in `require'
	from /home/moorem/Documents/koin/config/application.rb:7:in `<top (required)>'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:78:in `require'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/moorem/.rvm/gems/ruby-2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
` ` `

**Comment by joshua-bv** [comment]
hey @thilakg thanks for reporting the issue.  @jvergeldedios is diving into this and will help you to resolve it.
